AUTH='AUTH'
IDENTITY='IDENTITY'
BALANCE='BALANCE'
ACCOUNTS='ACCOUNTS'
TRANSACTIONS='TRANSACTIONS'
INCOME='INCOME'


# STATUS 
PENDING = 'PENDING'
APPROVE = 'APPROVE'
REJECT = 'REJECT'
INVITED = 'INVITED'

PDF_UPLOAD = 'pdf_upload'
INCOME_TRANSACTION = 'income_transaction'