# Generated by Django 4.2.1 on 2023-06-26 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('phone', models.CharField(max_length=26, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('verification_country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('INVITED', 'INVITED')], default='INVITED', max_length=20)),
                ('is_invited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('available_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('complete_onboarding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(max_length=10, null=True)),
                ('source', models.CharField(max_length=100)),
                ('monthly_amount', models.CharField(max_length=100, null=True)),
                ('average_monthly_income', models.FloatField(null=True)),
                ('account_age_months', models.IntegerField(null=True)),
                ('last_two_years_income', models.FloatField(null=True)),
                ('last_year_income', models.FloatField(null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='verifications.customer')),
            ],
        ),
    ]
