# Generated by Django 4.0.10 on 2023-05-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=26, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('verification_country', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_id', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('INVITED', 'INVITED')], default='PENDING', max_length=20)),
                ('is_invited', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(max_length=10, null=True)),
                ('summary', models.JSONField(null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('source', models.JSONField(null=True)),
                ('monthly_amount', models.CharField(max_length=100, null=True)),
                ('number_of_transactions', models.CharField(max_length=100, null=True)),
                ('primary_stream', models.CharField(max_length=100, null=True)),
                ('history', models.CharField(max_length=100, null=True)),
                ('working_days_this_year', models.IntegerField(null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='verifications.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField()),
                ('BvnNumber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='verifications.customer')),
            ],
        ),
    ]
