# Generated by Django 4.0.10 on 2023-05-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
