# Generated by Django 4.2.1 on 2023-07-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='country',
            new_name='risk_country_threshold',
        ),
        migrations.AlterField(
            model_name='customer',
            name='app_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='verifications.appid'),
            preserve_default=False,
        ),
    ]
