# Generated by Django 4.0.10 on 2023-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_rename_created_on_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
