# Generated by Django 4.2.1 on 2023-07-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_rename_country_customer_risk_country_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='app_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='verifications.appid'),
        ),
    ]
