# Generated by Django 4.2.1 on 2023-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo_id',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
