# Generated by Django 4.0.10 on 2023-06-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_alter_customer_identity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='identity_id',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=26),
        ),
    ]
