# Generated by Django 4.0.10 on 2023-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0004_rename_identity_id_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentCenter',
        ),
    ]
