# Generated by Django 4.0.10 on 2023-06-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0005_delete_enrollmentcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
