# Generated by Django 4.2.1 on 2023-07-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerincomedata',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerincomedata',
            name='customer',
            field=models.ManyToManyField(to='verifications.customer'),
        ),
    ]
