# Generated by Django 4.0.10 on 2023-06-03 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(max_length=10, null=True)),
                ('source', models.CharField(max_length=100)),
                ('monthly_amount', models.CharField(max_length=100, null=True)),
                ('average_monthly_income', models.FloatField(null=True)),
                ('account_age_months', models.IntegerField(null=True)),
                ('last_two_years_income', models.FloatField(null=True)),
                ('last_year_income', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nationality',
            new_name='available_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.DeleteModel(
            name='IncomeData',
        ),
        migrations.AddField(
            model_name='customerincomedata',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='verifications.customer'),
        ),
    ]
