# Generated by Django 4.0.10 on 2023-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0007_customerincomedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complete_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
