# Generated by Django 4.0.10 on 2023-06-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0008_customer_complete_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('INVITED', 'INVITED')], default='INVITED', max_length=20),
        ),
    ]
